name: Testing with Pytest
run-name: Pytest

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run pytest
      run: |
        pytest --junitxml=pytest-report.xml --verbose
      continue-on-error: false
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest-report.xml
        retention-days: 30
    
    - name: Test Summary
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "All tests passed successfully!"
        else
          echo "Some tests failed. Check the logs above."
        fi